### ISSUE TITLE
How to display nft attributes

### ISSUE THREAD

**Issue by watchoutformike** [thirdweb-example/marketplace#2]
Hi all, I recently forked the contract and am wondering how to display the nfts attributes when viewing them on the marketplace?

Currently there is nothing to display the traits of the nfts listed, which is always an important part of the purchasing process, to know if what you are buying is rare or common.

I imagine its just a call to the sdk to display and appreciate any help on how to achieve this

**Comment by jarrodwatts** [comment]
Hey @watchoutformike! 

You could use our NFT hooks for this, since the marketplace provides you with the contract address and token ID of the listed NFT.

Here is the link to the docs:

https://portal.thirdweb.com/react/react.usenft#example-2

It would look something like this:


```jsx
const nftCollection= useNFTCollection(<contractAddress>);
const { data: nft, isLoading, error } = useNFT(nftCollection, <tokenId>);
```
