### ISSUE TITLE
how to run the market place

### ISSUE THREAD

**Issue by khanfar** [thirdweb-example/marketplace#4]
how to run the market place ? whats the command ?

**Comment by jarrodwatts** [comment]
You can run `npm run dev` to run the marketplace!

**Comment by khanfar** [comment]
C:\Users\Lenovo\Downloads\Compressed\marketplace-main_2\marketplace-main>npm run dev

> dev
> next dev

'next' is not recognized as an internal or external command,
operable program or batch file.
