### ISSUE TITLE
Listings not loading. No errors

### ISSUE THREAD

**Issue by beauwilliams** [thirdweb-example/marketplace#7]
Hi it appears we are having this issue on our instance. I checked your one also and it has the same problem. Any ideas?

https://marketplace.thirdweb-example.com/

**Comment by jarrodwatts** [comment]
Hey @beauwilliams - I'm not seeing this on my end.

Any chance you can reach out to us on [Discord](https://discord.com/invite/thirdweb) to provide more info specific to your chain/contract/issue?

Just so you are aware, we are releasing a new V3 of our marketplace smart contract very soon. It is currently available for use on testnets, and I have been working on a new template for it as well, some more info below:

- Marketplace V3 template: https://github.com/thirdweb-example/marketplace-v3
- Marketplace V3 contract page: https://thirdweb.com/thirdweb.eth/MarketplaceV3

**Comment by beauwilliams** [comment]
I've been watching v3 closely! Was working on a marketplace contract over last year but we would like to absorb some of the awesome work you guys are doing. 

Ha, strange, yup works on my phone. I've been trying it for ages on my laptop and chrome devs tools was no help. I'll hop on the discord thanks 👍

**Comment by beauwilliams** [comment]
Seems to have been browser related. Closing. Thanks!

**Comment by nobady90** [comment]
@beauwilliams Are you by any chance using Brave?
